export type DatepickerRangeArgs = {
    'autofocus': boolean;
    'color': string;
    'disabled': boolean;
    'feedback': string;
    'feedback-text': string;
    'format': string;
    'helper-text': string;
    'highlighted-dates': string;
    'highlighted-weekends': boolean;
    'hide-panel': boolean;
    'hide-required': boolean;
    'label': string;
    'label-start': string;
    'label-end': string;
    'input-aria-label-start': string;
    'input-aria-label-end': string;
    'max': string;
    'min': string;
    'name': string;
    'placeholder-start': string;
    'placeholder-end': string;
    'readonly': boolean;
    'required': boolean;
    'required-start': boolean;
    'required-end': boolean;
    'size': string;
    'submit-on-enter': boolean;
    'tooltip-text': string;
    'type': string;
    'value': string;
    'disabled-dates': string;
    'athBlur'?: (event: CustomEvent<void>) => void;
    'athChange'?: (event: CustomEvent<void>) => void;
    'athFocus'?: (event: CustomEvent<void>) => void;
    'setFocus'?: () => void;
};
