import type { Meta, StoryObj } from '@storybook/html';
import { TableSelectionChangeEvent, TableClickEvent } from '../table.model';
type TableArgs = {
    'color': string;
    'frozen': string;
    'size': string;
    'striped': string;
    'selectable': string;
    'clickable': boolean;
    'no-select-all': boolean;
    'header': string;
    'body': string;
    'footer': string;
    'aria-label': string;
    'aria-labelledby': string;
    'tabindex': number;
    'refresh': () => void;
    'athSelectionChange': (event: CustomEvent<TableSelectionChangeEvent>) => void;
    'athTableClick': (event: CustomEvent<TableClickEvent>) => void;
};
declare const meta: Meta<TableArgs>;
export default meta;
type Story = StoryObj<TableArgs>;
export declare const Playground: Story;
export declare const Sizes: Story;
export declare const Colors: Story;
export declare const ColumnFixed: Story;
export declare const Striping: Story;
export declare const CustomWidthAndAlignment: Story;
export declare const WithMenuButton: Story;
export declare const SelectionSingle: Story;
export declare const SelectionMultiple: Story;
export declare const ClickableRows: Story;
export declare const RowWithHeaderCell: Story;
export declare const HeaderWithTooltip: Story;
export declare const RefreshMethod: Story;
export declare const CollapsableRows: Story;
