export { g as getAssetPath, r as render, s as setAssetPath, a as setNonce, b as setPlatformOptions } from './p-D-i5s4zr.js';
export { AthAccordion, defineCustomElement as defineCustomElementAthAccordion } from './ath-accordion.js';
export { AthAccordionItem, defineCustomElement as defineCustomElementAthAccordionItem } from './ath-accordion-item.js';
export { AthActionBar, defineCustomElement as defineCustomElementAthActionBar } from './ath-action-bar.js';
export { AthAlert, defineCustomElement as defineCustomElementAthAlert } from './ath-alert.js';
export { AthAvatar, defineCustomElement as defineCustomElementAthAvatar } from './ath-avatar.js';
export { AthBadge, defineCustomElement as defineCustomElementAthBadge } from './ath-badge.js';
export { AthBreadcrumb, defineCustomElement as defineCustomElementAthBreadcrumb } from './ath-breadcrumb.js';
export { AthButton, defineCustomElement as defineCustomElementAthButton } from './ath-button.js';
export { AthButtonExpandable, defineCustomElement as defineCustomElementAthButtonExpandable } from './ath-button-expandable.js';
export { AthButtonLink, defineCustomElement as defineCustomElementAthButtonLink } from './ath-button-link.js';
export { AthCalendar, defineCustomElement as defineCustomElementAthCalendar } from './ath-calendar.js';
export { AthCard, defineCustomElement as defineCustomElementAthCard } from './ath-card.js';
export { AthCardHeader, defineCustomElement as defineCustomElementAthCardHeader } from './ath-card-header.js';
export { AthCardSelectable, defineCustomElement as defineCustomElementAthCardSelectable } from './ath-card-selectable.js';
export { AthCardSelectableGroup, defineCustomElement as defineCustomElementAthCardSelectableGroup } from './ath-card-selectable-group.js';
export { AthCardThumbnail, defineCustomElement as defineCustomElementAthCardThumbnail } from './ath-card-thumbnail.js';
export { AthCheckbox, defineCustomElement as defineCustomElementAthCheckbox } from './ath-checkbox.js';
export { AthCheckboxGroup, defineCustomElement as defineCustomElementAthCheckboxGroup } from './ath-checkbox-group.js';
export { AthChipChoice, defineCustomElement as defineCustomElementAthChipChoice } from './ath-chip-choice.js';
export { AthChipChoiceGroup, defineCustomElement as defineCustomElementAthChipChoiceGroup } from './ath-chip-choice-group.js';
export { AthChipDismiss, defineCustomElement as defineCustomElementAthChipDismiss } from './ath-chip-dismiss.js';
export { AthChipDismissGroup, defineCustomElement as defineCustomElementAthChipDismissGroup } from './ath-chip-dismiss-group.js';
export { AthCollapse, defineCustomElement as defineCustomElementAthCollapse } from './ath-collapse.js';
export { AthCollapseIcon, defineCustomElement as defineCustomElementAthCollapseIcon } from './ath-collapse-icon.js';
export { AthDatepicker, defineCustomElement as defineCustomElementAthDatepicker } from './ath-datepicker.js';
export { AthDatepickerRange, defineCustomElement as defineCustomElementAthDatepickerRange } from './ath-datepicker-range.js';
export { AthDivider, defineCustomElement as defineCustomElementAthDivider } from './ath-divider.js';
export { AthDropdown, defineCustomElement as defineCustomElementAthDropdown } from './ath-dropdown.js';
export { AthDropdownOption, defineCustomElement as defineCustomElementAthDropdownOption } from './ath-dropdown-option.js';
export { AthEmptyState, defineCustomElement as defineCustomElementAthEmptyState } from './ath-empty-state.js';
export { AthIcon, defineCustomElement as defineCustomElementAthIcon } from './ath-icon.js';
export { AthInputCounter, defineCustomElement as defineCustomElementAthInputCounter } from './ath-input-counter.js';
export { AthInputPassword, defineCustomElement as defineCustomElementAthInputPassword } from './ath-input-password.js';
export { AthInputText, defineCustomElement as defineCustomElementAthInputText } from './ath-input-text.js';
export { AthInputTextarea, defineCustomElement as defineCustomElementAthInputTextarea } from './ath-input-textarea.js';
export { AthLink, defineCustomElement as defineCustomElementAthLink } from './ath-link.js';
export { AthList, defineCustomElement as defineCustomElementAthList } from './ath-list.js';
export { AthListItem, defineCustomElement as defineCustomElementAthListItem } from './ath-list-item.js';
export { AthMenuButton, defineCustomElement as defineCustomElementAthMenuButton } from './ath-menu-button.js';
export { AthMenuButtonItem, defineCustomElement as defineCustomElementAthMenuButtonItem } from './ath-menu-button-item.js';
export { AthMenuHorizontal, defineCustomElement as defineCustomElementAthMenuHorizontal } from './ath-menu-horizontal.js';
export { AthMenuHorizontalItem, defineCustomElement as defineCustomElementAthMenuHorizontalItem } from './ath-menu-horizontal-item.js';
export { AthMenuLateral, defineCustomElement as defineCustomElementAthMenuLateral } from './ath-menu-lateral.js';
export { AthMenuLateralItemAction, defineCustomElement as defineCustomElementAthMenuLateralItemAction } from './ath-menu-lateral-item-action.js';
export { AthMenuLateralItemLink, defineCustomElement as defineCustomElementAthMenuLateralItemLink } from './ath-menu-lateral-item-link.js';
export { AthMenuVertical, defineCustomElement as defineCustomElementAthMenuVertical } from './ath-menu-vertical.js';
export { AthMenuVerticalItemAction, defineCustomElement as defineCustomElementAthMenuVerticalItemAction } from './ath-menu-vertical-item-action.js';
export { AthMenuVerticalItemLink, defineCustomElement as defineCustomElementAthMenuVerticalItemLink } from './ath-menu-vertical-item-link.js';
export { AthModal, defineCustomElement as defineCustomElementAthModal } from './ath-modal.js';
export { AthPagination, defineCustomElement as defineCustomElementAthPagination } from './ath-pagination.js';
export { AthPanel, defineCustomElement as defineCustomElementAthPanel } from './ath-panel.js';
export { AthPictogram, defineCustomElement as defineCustomElementAthPictogram } from './ath-pictogram.js';
export { AthProgressBar, defineCustomElement as defineCustomElementAthProgressBar } from './ath-progress-bar.js';
export { AthRadioButton, defineCustomElement as defineCustomElementAthRadioButton } from './ath-radio-button.js';
export { AthRadioButtonGroup, defineCustomElement as defineCustomElementAthRadioButtonGroup } from './ath-radio-button-group.js';
export { AthSectionTitle, defineCustomElement as defineCustomElementAthSectionTitle } from './ath-section-title.js';
export { AthSegmentedControl, defineCustomElement as defineCustomElementAthSegmentedControl } from './ath-segmented-control.js';
export { AthSegmentedControlItem, defineCustomElement as defineCustomElementAthSegmentedControlItem } from './ath-segmented-control-item.js';
export { AthSlider, defineCustomElement as defineCustomElementAthSlider } from './ath-slider.js';
export { AthStep, defineCustomElement as defineCustomElementAthStep } from './ath-step.js';
export { AthStepper, defineCustomElement as defineCustomElementAthStepper } from './ath-stepper.js';
export { AthSwitch, defineCustomElement as defineCustomElementAthSwitch } from './ath-switch.js';
export { AthTab, defineCustomElement as defineCustomElementAthTab } from './ath-tab.js';
export { AthTable, defineCustomElement as defineCustomElementAthTable } from './ath-table.js';
export { AthTableBody, defineCustomElement as defineCustomElementAthTableBody } from './ath-table-body.js';
export { AthTableHeader, defineCustomElement as defineCustomElementAthTableHeader } from './ath-table-header.js';
export { AthTableHeaderItem, defineCustomElement as defineCustomElementAthTableHeaderItem } from './ath-table-header-item.js';
export { AthTableRow, defineCustomElement as defineCustomElementAthTableRow } from './ath-table-row.js';
export { AthTableRowItem, defineCustomElement as defineCustomElementAthTableRowItem } from './ath-table-row-item.js';
export { AthTabs, defineCustomElement as defineCustomElementAthTabs } from './ath-tabs.js';
export { AthTag, defineCustomElement as defineCustomElementAthTag } from './ath-tag.js';
export { AthText, defineCustomElement as defineCustomElementAthText } from './ath-text.js';
export { AthTooltip, defineCustomElement as defineCustomElementAthTooltip } from './ath-tooltip.js';
export { AthTooltipTrigger, defineCustomElement as defineCustomElementAthTooltipTrigger } from './ath-tooltip-trigger.js';
export { AthUserDetail, defineCustomElement as defineCustomElementAthUserDetail } from './ath-user-detail.js';
export { AthUserMenu, defineCustomElement as defineCustomElementAthUserMenu } from './ath-user-menu.js';

function format(first, middle, last) {
    return (first || '') + (middle ? ` ${middle}` : '') + (last ? ` ${last}` : '');
}

export { format };
//# sourceMappingURL=index.js.map

//# sourceMappingURL=index.js.map