import type { Meta, StoryObj } from '@storybook/html';
import { MenuVerticalItemActionArgs } from './menu-vertical-item-action.types';
declare const meta: Meta<MenuVerticalItemActionArgs>;
export default meta;
type Story = StoryObj<MenuVerticalItemActionArgs>;
export declare const Playground: Story;
export declare const Disabled: Story;
export declare const Icon: Story;
export declare const Nivel1: Story;
export declare const Nivel2: Story;
export declare const Nivel3: Story;
export declare const Open: Story;
export declare const Selected: Story;
