export type InputTextArgs = {
    'autofocus': boolean;
    'autocomplete': string;
    'clear-button-aria-label': string;
    'counter': boolean;
    'counter-label': string;
    'disabled': boolean;
    'feedback': string;
    'feedback-text': string;
    'has-clear': boolean;
    'helper-text': string;
    'icon': string;
    'icon-position': string;
    'input-aria-label': string;
    'input-tabindex': string;
    'label': string;
    'maxlength': number;
    'name': string;
    'placeholder': string;
    'readonly': boolean;
    'required': boolean;
    'hide-required': boolean;
    'size': string;
    'submit-on-enter': boolean;
    'tooltip-text': string;
    'tooltip-width': number;
    'type': string;
    'value': string;
    'athFocus'?: (event: CustomEvent<void>) => void;
    'athBlur'?: (event: CustomEvent<void>) => void;
    'athChange'?: (event: CustomEvent<void>) => void;
    'athClear'?: (event: CustomEvent<void>) => void;
    'athInput'?: (event: CustomEvent<void>) => void;
    'setFocus'?: () => void;
};
export declare const ordererArgs: Partial<InputTextArgs>;
