import type { Meta, StoryObj } from '@storybook/html';
import { InputTextArgs } from './input-text.types';
declare const meta: Meta<InputTextArgs>;
export default meta;
type Story = StoryObj<InputTextArgs>;
export declare const Playground: Story;
export declare const Autofocus: Story;
export declare const ConClearButton: Story;
export declare const ConCounter: Story;
export declare const Disabled: Story;
export declare const ConFeedback: Story;
export declare const NoEnfocable: Story;
export declare const ConHelperText: Story;
export declare const ConIcon: Story;
export declare const ConLabel: Story;
export declare const Placeholder: Story;
export declare const ReadOnly: Story;
export declare const Required: Story;
export declare const SearchType: Story;
export declare const Size: Story;
export declare const ConTooltip: Story;
