import type { Meta, StoryObj } from '@storybook/html';
import { DropdownArgs } from './dropdown.types';
declare const meta: Meta<DropdownArgs>;
export default meta;
type Story = StoryObj<DropdownArgs>;
export declare const Playground: Story;
export declare const ConBusqueda: Story;
export declare const ConFeedback: Story;
export declare const ConHelperText: Story;
export declare const ConTooltip: Story;
export declare const Disabled: Story;
export declare const Multiselect: Story;
export declare const Readonly: Story;
export declare const ConChips: Story;
export declare const Size: Story;
export declare const WidthYOverlayMaxHeight: Story;
